# Generated by Django 5.1.4 on 2025-01-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargotype',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image of the cargo type', null=True, upload_to='cargo_types/'),
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image of the service', null=True, upload_to='services/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image of the vehicle', null=True, upload_to='vehicles/'),
        ),
    ]
